"""wagons + groups + tracking_assignments

Revision ID: 850dceeb9555
Revises: b80605cd35d4
Create Date: 2026-05-12 10:53:06.456199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '850dceeb9555'
down_revision: Union[str, Sequence[str], None] = 'b80605cd35d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wagons',
    sa.Column('number', sa.String(length=20), nullable=False, comment='Номер вагона / контейнера'),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False, comment='Когда впервые увидели этот вагон в наших данных'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False, comment='Когда последний раз обновляли данные дислокации'),
    sa.Column('last_source', sa.String(length=20), nullable=True, comment='Источник последнего обновления: api / ftp / manual'),
    sa.Column('is_full_name', sa.String(length=20), nullable=True, comment='Груж/Пор'),
    sa.Column('doc_number', sa.String(length=50), nullable=True, comment='Номер накладной'),
    sa.Column('loading_date', sa.DateTime(timezone=True), nullable=True, comment='Дата погрузки/выгрузки'),
    sa.Column('loading_station', sa.String(length=20), nullable=True, comment='Код станции погрузки/выгрузки'),
    sa.Column('loading_station_name', sa.String(length=255), nullable=True, comment='Станция погрузки/выгрузки'),
    sa.Column('loading_rw_name', sa.String(length=100), nullable=True, comment='Дорога погрузки/выгрузки'),
    sa.Column('loading_country_name', sa.String(length=100), nullable=True, comment='ЖД администрация ст. погрузки/выгрузки'),
    sa.Column('disl_rw', sa.String(length=20), nullable=True, comment='Код дороги дислокации'),
    sa.Column('disl_rw_name', sa.String(length=100), nullable=True, comment='Дорога дислокации'),
    sa.Column('disl_country_name', sa.String(length=100), nullable=True, comment='ЖД администрация дислокации'),
    sa.Column('oper_station', sa.String(length=20), nullable=True, comment='Код станции операции'),
    sa.Column('oper_station_name', sa.String(length=255), nullable=True, comment='Станция операции'),
    sa.Column('oper_station_department', sa.String(length=255), nullable=True, comment='Отделение станции операции'),
    sa.Column('oper_code', sa.String(length=10), nullable=True, comment='Код операции'),
    sa.Column('oper_name', sa.String(length=100), nullable=True, comment='Операция'),
    sa.Column('oper_full_name', sa.String(length=512), nullable=True, comment='Полное наименование операции'),
    sa.Column('oper_date', sa.DateTime(timezone=True), nullable=True, comment='Дата операции'),
    sa.Column('cargo_weight', sa.Double(), nullable=True, comment='Вес груза (кг)'),
    sa.Column('cargo_code', sa.String(length=20), nullable=True, comment='Код груза учётный ЕТСНГ'),
    sa.Column('cargo_name', sa.String(length=255), nullable=True, comment='Груз'),
    sa.Column('cargo_full_name', sa.String(length=512), nullable=True, comment='Полное наименование груза'),
    sa.Column('train_num', sa.String(length=20), nullable=True, comment='Номер поезда'),
    sa.Column('train_index', sa.String(length=60), nullable=True, comment='Индекс поезда'),
    sa.Column('train_index_1', sa.String(length=20), nullable=True, comment='Индекс поезда (ст. форм.)'),
    sa.Column('train_index_2', sa.String(length=20), nullable=True, comment='Индекс поезда (№ н. листа)'),
    sa.Column('train_index_3', sa.String(length=20), nullable=True, comment='Индекс поезда (ст. назн.)'),
    sa.Column('npp', sa.String(length=10), nullable=True, comment='НПП'),
    sa.Column('train_from_station_name', sa.String(length=255), nullable=True, comment='Станция формирования поезда'),
    sa.Column('train_to_station_name', sa.String(length=255), nullable=True, comment='Станция расформирования поезда'),
    sa.Column('car_number', sa.String(length=20), nullable=True, comment='Номер платформы (для контейнеров)'),
    sa.Column('dest_rw', sa.String(length=20), nullable=True, comment='Код дороги назначения'),
    sa.Column('dest_rw_name', sa.String(length=100), nullable=True, comment='Дорога назначения'),
    sa.Column('dest_country_name', sa.String(length=100), nullable=True, comment='ЖД администрация ст. назначения'),
    sa.Column('dest_station', sa.String(length=20), nullable=True, comment='Код станции назначения'),
    sa.Column('dest_station_name', sa.String(length=255), nullable=True, comment='Станция назначения'),
    sa.Column('dest_station_department', sa.String(length=255), nullable=True, comment='Отделение станции назначения'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='Срок доставки'),
    sa.Column('rest_distance', sa.Double(), nullable=True, comment='Остаточное расстояние (км)'),
    sa.Column('rest_run', sa.Double(), nullable=True, comment='Остаток пробега (км)'),
    sa.Column('grpol_okpo', sa.String(length=20), nullable=True, comment='ОКПО грузополучателя'),
    sa.Column('grpol_name', sa.String(length=255), nullable=True, comment='Наименование грузополучателя'),
    sa.Column('grpol_rw', sa.String(length=20), nullable=True, comment='ЖД код грузополучателя'),
    sa.Column('grotpr_okpo', sa.String(length=20), nullable=True, comment='ОКПО грузоотправителя'),
    sa.Column('grotpr_name', sa.String(length=255), nullable=True, comment='Наименование грузоотправителя'),
    sa.Column('grotpr_rw', sa.String(length=20), nullable=True, comment='ЖД код грузоотправителя'),
    sa.Column('rash_rw', sa.String(length=20), nullable=True, comment='Код дороги — источника данных'),
    sa.Column('rash_date', sa.DateTime(timezone=True), nullable=True, comment='Дата обновления данных'),
    sa.Column('start_date_on_station', sa.DateTime(timezone=True), nullable=True, comment='Дата прибытия на текущую станцию'),
    sa.Column('day_count_on_station', sa.Double(), nullable=True, comment='Кол-во дней на станции'),
    sa.Column('days_wo_operation', sa.Double(), nullable=True, comment='Дней без операции'),
    sa.Column('days_from_start', sa.Double(), nullable=True, comment='Кол-во дней после погрузки'),
    sa.Column('days_on_trade_union', sa.Double(), nullable=True, comment='Кол-во дней на территории ТС (Таможенный Союз)'),
    sa.Column('cl_start_at', sa.DateTime(timezone=True), nullable=True, comment='Дата захода на текущую страну'),
    sa.Column('faulty_name', sa.String(length=255), nullable=True, comment='Неисправность'),
    sa.Column('car_type_name', sa.String(length=100), nullable=True, comment='Род вагона'),
    sa.Column('date_build', sa.Date(), nullable=True, comment='Дата постройки'),
    sa.Column('capacity', sa.Double(), nullable=True, comment='Грузоподъёмность вагона (тонн)'),
    sa.Column('volume', sa.Double(), nullable=True, comment='Объём кузова (м³)'),
    sa.Column('extended_life_time', sa.Date(), nullable=True, comment='Срок службы вагона'),
    sa.Column('date_plan_repair', sa.Date(), nullable=True, comment='Дата следующего ремонта'),
    sa.Column('nsp_indicator', sa.String(length=50), nullable=True, comment='Признак НСП'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Сырой объект из источника на случай если понадобятся поля сверх схемы'),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_wagons_number'), 'wagons', ['number'], unique=True)
    op.create_table('wagon_groups',
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Компания-владелец группы'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название группы'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='HEX-цвет для UI (#RRGGBB)'),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('company_id', 'name', name='uq_wagon_groups_company_name'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_wagon_groups_company_id'), 'wagon_groups', ['company_id'], unique=False)
    op.create_table('tracking_assignments',
    sa.Column('company_id', sa.Uuid(), nullable=False, comment='Компания, которая следит'),
    sa.Column('wagon_number', sa.String(length=20), nullable=False, comment='Номер вагона (бизнес-идентификатор)'),
    sa.Column('group_id', sa.Uuid(), nullable=True, comment='Группа в которой вагон у этой компании'),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Активно ли слежение'),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True, comment='Когда слежение было снято'),
    sa.Column('initial_territory', sa.String(length=100), nullable=True, comment='Страна на момент постановки (для биллинга)'),
    sa.Column('remove_on_route_end', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Автоматически снять когда вагон достигнет dest_station'),
    sa.Column('deferred_start_at', sa.DateTime(timezone=True), nullable=True, comment='Отложенный старт слежения (активируется не сразу)'),
    sa.Column('auto_remove_at', sa.DateTime(timezone=True), nullable=True, comment='Автоматически снять в указанную дату'),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['wagon_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('company_id', 'wagon_number', name='uq_tracking_company_wagon'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tracking_assignments_company_id'), 'tracking_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_tracking_assignments_group_id'), 'tracking_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_tracking_assignments_wagon_number'), 'tracking_assignments', ['wagon_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_assignments_wagon_number'), table_name='tracking_assignments')
    op.drop_index(op.f('ix_tracking_assignments_group_id'), table_name='tracking_assignments')
    op.drop_index(op.f('ix_tracking_assignments_company_id'), table_name='tracking_assignments')
    op.drop_table('tracking_assignments')
    op.drop_index(op.f('ix_wagon_groups_company_id'), table_name='wagon_groups')
    op.drop_table('wagon_groups')
    op.drop_index(op.f('ix_wagons_number'), table_name='wagons')
    op.drop_table('wagons')
    # ### end Alembic commands ###
